export enum StatusUsuario {
  ATIVO = "ATIVO",
  SOLICITADO_PREMIUM = "SOLICITADO_PREMIUM",
  AGUARDANDO_ANALISE = "AGUARDANDO_ANALISE",
  EM_ANALISE = "EM_ANALISE",
  APROVADO = "APROVADO",
  RECUSADO = "RECUSADO",
  DESATIVADO = "DESATIVADO",
  PRIMEIRO_ACESSO = "PRIMEIRO_ACESSO",
  PRIMEIRO_ACESSO_PREMIUM = "PRIMEIRO_ACESSO_PREMIUM",
}
