export enum StatusDocumento {
  ATIVO = "ATIVO",
  AGUARDANDO_ANALISE = "AGUARDANDO_ANALISE",
  EM_ANALISE = "EM_ANALISE",
  APROVADO = "APROVADO",
  RECUSADO = "RECUSADO",
  DESATIVADO = "DESATIVADO",
}
