export enum StatusCarteiraInvestimento {
  EM_ESTRUTURACAO = "EM_ESTRUTURACAO",
  AGUARDANDO_ASSINATURA = "AGUARDANDO_ASSINATURA",
  AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO",
  COMPRA_EFETUADA = "COMPRA_EFETUADA",
  COMPRA_RECUSADA = "COMPRA_RECUSADA",
}
