export enum TipoUsuario {
  INVESTIDOR_TRIAL = "INVESTIDOR_TRIAL",
  INVESTIDOR_PREMIUM = "INVESTIDOR_PREMIUM",
  BACKOFFICE = "BACKOFFICE",
  COMPLIANCE = "COMPLIANCE",
  GESTOR = "GESTOR",
  ADMINISTRADOR_SISTEMAS = "ADMINISTRADOR_SISTEMAS",
}
