export enum TipoUsuarioEnum {
  INVESTIDOR_TRIAL = 'INVESTIDOR_TRIAL',
  INVESTIDOR_PREMIUM = 'INVESTIDOR_PREMIUM',
  BACKOFFICE = 'BACKOFFICE',
  COMPLIANCE = 'COMPLIANCE',
  GESTOR = 'GESTOR',
  ADMINISTRADOR_SISTEMAS = 'ADMINISTRADOR_SISTEMAS',
}

export type TipoUsuario =
  | 'INVESTIDOR_TRIAL'
  | 'INVESTIDOR_PREMIUM'
  | 'BACKOFFICE'
  | 'COMPLIANCE'
  | 'GESTOR'
  | 'ADMINISTRADOR_SISTEMAS';
