import { CarteiraInvestimento } from './CarteiraInvestimento';
import { AdministradorFundo } from './administradorFundo';
import { ContaInvestidor } from './contaInvestidor';
import { ContaRepasse } from './contaRepasse';
import { DebentureSerieInvestidor } from './debenture';
import { Documento } from './documento';
import { FeedbackBackoffice } from './feedbackBackoffice';
import { FundoBackoffice } from './fundoBackoffice';
import { FundoInvestimentoGestorFundo } from './fundoInvestimentoGestorFundo';
import { ProcuradorFundoFundoInvestimento } from './procuradorFundoFundoInvestimento';
import { RepresentanteFundo } from './representanteFundo';

export type FundoInvestimento = {
  id: number;
  nome?: string;
  razao_social?: string;
  nome_fantasia?: string;
  codigo_anbima?: string;
  classe_anbima?: string;
  atividade_principal?: string;
  id_status_fundo_investimento?: number;
  id_fundo_backoffice?: number;
  id_administrador_fundo?: number;
  detalhes?: string;
  data_criacao?: Date;
  cpf_cnpj?: string;
  id_representante_fundo?: number;
  tipo_estrutura?: string;
  faturamento_anual?: string;
  apto_debenture: boolean;
  valor_serie_debenture?: number;
  nota_investidor_suitability?: number;
  perfil_investidor_suitability?: string;
  data_expiracao_suitability?: Date;
  carteira_investimento?: CarteiraInvestimento[];
  conta_investidor?: ContaInvestidor[];
  conta_repasse?: ContaRepasse;
  debenture_serie_investidor?: DebentureSerieInvestidor[];
  documento?: Documento[];
  feedback_backoffice?: FeedbackBackoffice[];
  administrador_fundo?: AdministradorFundo;
  fundo_backoffice?: FundoBackoffice;
  status_fundo_investimento?: StatusFundoInvestimento;
  representante_fundo?: RepresentanteFundo;
  fundo_investimento_gestor_fundo?: FundoInvestimentoGestorFundo[];
  procurador_fundo_fundo_investimento?: ProcuradorFundoFundoInvestimento[];
};

export type StatusFundoInvestimento = {
  id: number;
  nome: string;
  descricao: string;
  fundo_investimento?: FundoInvestimento[];
};
